---
# Should /var/lib/minecraft be an NFS mount or a real directory?
minecraft_nfs_home: false
# Minecraft NFS mount point
minecraft_nfs_mount_point: /mnt/minecraft-nfs
# Minecraft home directory
minecraft_home: /var/lib/minecraft
# Minecraft lib directory
minecraft_lib: /usr/local/lib/minecraft
# Minecraft Server System user
minecraft_server_icon_file_name: "server-icon.png"
minecraft_user_pass: "creeper"
minecraft_user_name: "minecraft"
