---
- name: Generate new Spigot jar from patch
  command: java -jar /usr/local/lib/minecraft/spigot/SpigotPatcher.jar /usr/local/lib/minecraft/spigot/jars/spigot1649.jar /usr/local/lib/minecraft/spigot/patches/spigot-{{ spigot_patch_version }}.bps /usr/local/lib/minecraft/spigot/spigot-{{ spigot_patch_version }}.jar creates=/usr/local/lib/minecraft/spigot/spigot-{{ spigot_patch_version }}.jar
- name: Check patched Spigot jar md5
  stat: path=/usr/local/lib/minecraft/spigot/spigot-{{ spigot_patch_version }}.jar
  register: spigot
- name: Fail if patched Spigot jar md5 is incorrect
  fail: msg="Patched spigot jar md5 is not correct"
  when: spigot.stat.md5 != '{{ spigot_patched_jar_md5 }}'

